import fs from 'node:fs';import assert from 'node:assert/strict';
const read=n=>JSON.parse(fs.readFileSync(new URL('../data/'+n,import.meta.url)));
const d=read('conditions.json'),s=read('sources.json'),old=read('legacy.json'),coverage=read('coverage.json');const byid=new Map(s.map(x=>[x.id,x]));
assert.equal(d.length,299);assert.equal(old.length,289);assert.equal(new Set(d.map(x=>x.id)).size,d.length);assert.equal(byid.size,s.length);
for(const c of d){assert(c.references.length,`${c.title}: missing sources`);for(const r of c.references){assert(byid.has(r.sourceId),`${c.title}: broken source ${r.sourceId}`);if(r.page)assert(Number.isInteger(r.page)&&r.page>0);}assert(c.summary?c.regimenStatus==='source-summary':c.regimenStatus==='not-revalidated');if(c.summary){assert(byid.has(c.summary.sourceId));assert(c.summary.scope);assert(c.summary.edition);for(const r of c.summary.regimens){assert(r.dose);assert(r.duration);assert(r.population);assert(r.cautions);}}}
for(const source of s){const u=new URL(source.url);assert.equal(u.protocol,'https:');assert(['www.icmr.gov.in','clinicalestablishments.mohfw.gov.in'].includes(u.hostname));assert(!u.pathname.endsWith('/.pdf'));assert(!/^\d{10}$/.test(source.edition||''),'Do not infer publication from upload timestamp');}
assert.equal(d.filter(x=>x.summary).length,coverage.summaryCount);for(const status of Object.keys(coverage.statusCounts))assert.equal(d.filter(x=>x.sourceStatus===status).length,coverage.statusCounts[status]);
assert.equal(d.find(x=>x.title==='Fever').category,'Common Conditions');assert.equal(d.find(x=>x.title==='Infective Endocarditis').category,'Cardiovascular Diseases');assert.equal(d.find(x=>x.title==='Migraine').category,'Central Nervous System Diseases');assert.equal(d.find(x=>x.title==='Toothache').category,'Dental Conditions');
const pediatric=d.find(x=>x.title==='Diabetes Mellitus'&&x.category==='Pediatric Conditions');assert.equal(pediatric.summary,null,'Do not copy adult type 2 diabetes treatment into pediatric entry');assert(pediatric.references.filter(x=>x.sourceId.startsWith('icmr-diabetes')).every(x=>x.relation==='related-workflow'));
const ht=d.find(x=>x.title==='Hypertension');assert(ht.summary.regimens[0].titration.includes('10 mg'));assert.equal(ht.summary.regimens[0].sourcePage,132);
assert.equal(d.find(x=>x.title==='Scabies').summary.regimens[0].duration,'Two applications separated by 7–14 days');
const config=JSON.parse(fs.readFileSync(new URL('../vercel.json',import.meta.url)));assert(!config.rewrites.some(r=>r.source==='/(.*)'),'Static JSON must not be rewritten to HTML');
console.log(`PASS: ${d.length} entries, ${s.length} source URLs, complete original coverage, population boundaries, dose provenance, status counts, and Vercel static routing.`);
